In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.arange(10)
d = np.linspace(0, 1, 5)
e = np.zeros((2, 3))
f = np.ones((2, 3))
g = np.eye(3)
h = np.empty((2, 2))
i = np.full((2, 2), 7)
j = np.random.random((2, 2))
k = np.random.randint(0, 10, (2, 2))
l = np.random.randn(2, 2)
m = np.random.rand(2, 2)
print("b",b)
print("c",c)
print("d",d)
print("e",e)
print("f",f)
print("g",g)
print("h",h)
print("i",i)
print("j",j)
print("k",k)
print("l",l)
print("m",m)
print("Array a:", a)
print("Shape of a:", a.shape)
print("Size of a:", a.size)
print("Data type of a:", a.dtype)
print("Number of dimensions of a:", a.ndim)
print("Number of bytes of a:", a.nbytes)
print(c)
print("Addition:", np.add(a, 2))
print("Subtraction:", np.subtract(a, 2))
print("Multiplication:", np.multiply(a, 2))
print("Division:", np.divide(a, 2))
print("Power:", np.power(a, 2))
print("Square root:", np.sqrt(a))
print("Logarithm:", np.log(np.array([1, np.e])))
print("Exponential:", np.exp(a))
print("Absolute value:", np.abs(np.array([-1, -2, 3])))
print("Rounded:", np.around(np.array([1.1234, 2.5678]), decimals=2))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard deviation:", np.std(a))
print("Variance:", np.var(a))
print("Sum:", np.sum(a))
print("Product:", np.prod(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))

print("Reshaped:", np.reshape(a, (3, 1)))
print("Flattened:", np.ravel(b))

print("Slice:", a[1:3])
print("Indexing:", a[[0, 2]])

print("Concatenated:", np.concatenate((a, np.array([4, 5]))))
print("Split:", np.split(np.arange(12), 3))

print("Dot product:", np.dot(a, np.array([1, 1, 1])))
print("Inverse of identity matrix:", np.linalg.inv(np.eye(2)))
print("Eigenvalues and eigenvectors:", np.linalg.eig(np.array([[1, 2], [3, 4]])))

print("Where:", np.where(a > 1, 'yes', 'no'))
print("Searchsorted:", np.searchsorted(np.array([1, 2, 3]), 2))
print("Unique:", np.unique(np.array([1, 2, 2, 3, 3, 3])))

print("Transpose:", np.transpose(b))

print("Repeated:", np.repeat(a, 2))
print("Diagonal:", np.diag([1, 2, 3]))
print("Triangular matrix:", np.tri(3))
print("Upper triangular matrix:", np.triu(np.array([[1, 2], [3, 4]])))
print("Lower triangular matrix:", np.tril(np.array([[1, 2], [3, 4]])))

print("Bitwise AND:", np.bitwise_and(a, np.array([1, 1, 1])))
print("Bitwise OR:", np.bitwise_or(a, np.array([0, 1, 0])))
print("Bitwise XOR:", np.bitwise_xor(a, np.array([1, 0, 1])))
print("Bitwise NOT:", np.bitwise_not(a))

print("Broadcast addition:", a + np.array([10]))
print("Broadcast multiplication:", a * np.array([2, 2, 2]))

print("NaN check:", np.isnan(np.array([1, np.nan])))
print("Inf check:", np.isinf(np.array([1, np.inf])))
print("NaN to num:", np.nan_to_num(np.array([1, np.nan])))




b [[1 2]
 [3 4]]
c [0 1 2 3 4 5 6 7 8 9]
d [0.   0.25 0.5  0.75 1.  ]
e [[0. 0. 0.]
 [0. 0. 0.]]
f [[1. 1. 1.]
 [1. 1. 1.]]
g [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
h [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
i [[7 7]
 [7 7]]
j [[0.64001177 0.4885859 ]
 [0.781411   0.67986992]]
k [[4 2]
 [0 4]]
l [[-1.23254201  2.28396582]
 [-0.27442701 -0.3013937 ]]
m [[0.6595868  0.18755019]
 [0.42056755 0.59567368]]
Array a: [1 2 3]
Shape of a: (3,)
Size of a: 3
Data type of a: int64
Number of dimensions of a: 1
Number of bytes of a: 24
[0 1 2 3 4 5 6 7 8 9]
Addition: [3 4 5]
Subtraction: [-1  0  1]
Multiplication: [2 4 6]
Division: [0.5 1.  1.5]
Power: [1 4 9]
Square root: [1.         1.41421356 1.73205081]
Logarithm: [0. 1.]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Absolute value: [1 2 3]
Rounded: [1.12 2.57]
Mean: 2.0
Median: 2.0
Standard deviation: 0.816496580927726
Variance: 0.6666666666666666
Sum: 6
Product: 6
Minimum: 1
Maximum: 3
Reshaped: [[1]
 [2]
 [3]]
Flattened: [1 2 3 4]
Slice: