In [ ]:
import joblib
from sklearn.datasets import load_iris
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score

iris = load_iris()
X = iris.data
y = iris.target
scaler_std = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train_scaled_std = scaler_std.fit_transform(X_train)
X_test_scaled_std = scaler_std.transform(X_test)

scaler_minmax = MinMaxScaler()
X_train_scaled_minmax = scaler_minmax.fit_transform(X_train)
X_test_scaled_minmax = scaler_minmax.transform(X_test)

classifier_knn = KNeighborsClassifier(n_neighbors=3)
classifier_knn.fit(X_train_scaled_std, y_train)
y_pred = classifier_knn.predict(X_test_scaled_std)

joblib.dump(classifier_knn, 'knn_model.pkl')
loaded_model = joblib.load('knn_model.pkl')

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

kfold = KFold(n_splits=5, shuffle=True, random_state=1)

knn_classifier = KNeighborsClassifier(n_neighbors=3)

scores = cross_val_score(knn_classifier, X, y, cv=kfold, scoring='accuracy')

print("Average accuracy:", np.mean(scores))

Accuracy: 1.0
Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Average accuracy: 0.9600000000000002


In [2]:
!pip install manim


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 11.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [1]:
from manim import *

class SineWave(Scene):
    def construct(self):
        # Axes for the sine wave
        axes = Axes(
            x_range=[0, 10, 1],  # x-axis range and step size
            y_range=[-2, 2, 1],  # y-axis range and step size
            axis_config={"color": WHITE},
        )

        # Add labels to the axes
        labels = axes.get_axis_labels(x_label="x", y_label="sin(x)")

        # Create the sine wave function
        sine_wave = axes.plot(
            lambda x: np.sin(x),
            x_range=[0, 10],
            color=BLUE,
        )

        # Animate the sine wave
        sine_wave_wave_animation = ValueTracker(0)

        def updating_wave():
            return axes.plot(
                lambda x: np.sin(x + sine_wave_wave_animation.get_value()),
                x_range=[0, 10],
                color=BLUE,
            )

        animated_wave = always_redraw(updating_wave)

        # Add the components to the scene
        self.add(axes, labels, sine_wave)
        self.add(animated_wave)

        # Create an animation that moves the wave
        self.play(sine_wave_wave_animation.animate.increment_value(2 * PI), run_time=4, rate_func=linear)
        self.wait()


ModuleNotFoundError: No module named 'manim'