In [4]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print(tensor_1d)
tensor_1d[0]
tensor_1d[2]

tensor_2d=np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)
tensor_2d[3][2]

import tensorflow as tf

matrix1 = np.array([(2,5,7),(9,1,2),(1,5,7)],dtype='int32')
matrix2 = np.array([(2,3,4),(1,4,7),(8,2,4)],dtype='int32')
print(matrix1)
print(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32')
print(matrix_product)
print(matrix_sum)

[ 1.3   1.    4.   23.99]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2 5 7]
 [9 1 2]
 [1 5 7]]
[[2 3 4]
 [1 4 7]
 [8 2 4]]
tf.Tensor(
[[65 40 71]
 [35 35 51]
 [63 37 67]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 4  8 11]
 [10  5  9]
 [ 9  7 11]], shape=(3, 3), dtype=int32)
